### Get all available surveys
GET http://localhost:3001/api/surveys/all

### Search existing survey by ID
GET http://localhost:3001/api/surveys?id=1

### Search unexisting survey by ID
GET http://localhost:3001/api/surveys?id=1222

### Search survey by wrong ID
GET http://localhost:3001/api/surveys?id=12sada2

### Unknown route
GET http://localhost:3001/api/notavalidapi

### New survey from registered user
POST http://localhost:3001/api/surveys/new
Content-Type: application/json

{
    "title": "Questions about science",
    "questions": [
        {
            "title": "Do you read Focus magazine?",
            "min": 1,
            "max": 1,
            "options": [
                {
                    "text": "Yes"
                },
                {
                    "text": "No"
                }
            ]
        },
        {
            "title": "How do you describe the capability of the sun to rise?",
            "mandatory": 0
        },
        {
            "title": "What's the g on heart?",
            "min": 0,
            "max": 1,
            "options": [
                {
                    "text": "9.81 m/s^2"
                },
                {
                    "text": "11 m/s^2"
                },
                {
                    "text": "200 km/h"
                }
            ]
        }
    ]
}

### New survey with no name from registered user (should fail)
POST http://localhost:3001/api/surveys/new
Content-Type: application/json

{
    "questions": [
        {
            "title": "Do you read Focus magazine?",
            "min": 1,
            "max": 1,
            "options": [
                {
                    "text": "Yes"
                },
                {
                    "text": "No"
                }
            ]
        },
        {
            "title": "How do you describe the capability of the sun to rise?",
            "mandatory": 0
        }
    ]
}

### New survey with no questions from registered user (should fail)
POST http://localhost:3001/api/surveys/new
Content-Type: application/json

{
    "title": "Questions about science", 
    "questions": [
        
    ]
}

### New answer from unregistered user to survey 2
POST http://localhost:3001/api/surveys/answer?id=2
Content-Type: application/json

{
    "name": "Mark",
    "answers": [
        {
            "questionId": 1,
            "selOptions": [
                1
            ]
        },
        {
            "questionId": 2,
            "openAnswer": "Don't know"
        },
        {
            "questionId": 3,
            "selOptions": [
                1
            ]
        }
    ]
}